#!/bin/sh

# Run formatting on staged files
echo "Running npm run format..."
npm run format

# Add any formatting changes back to staging
git add .

# Run linting
echo "Running npm run lint..."
npm run lint

# Run tests
echo "Running tests..."
npm test
